FROM golang:1.12
COPY . /opt/app
WORKDIR /opt/app
RUN go mod download
RUN go get -u github.com/codegangsta/gin
RUN curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin
CMD gin -d cmd/httpd
