version: '2'
services:
  httpd:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      TZ: Europe/Prague
      GOFLAGS: -mod=readonly
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
      - ~/go/pkg:/go/pkg:ro
    networks:
      - lab
  storage:
    image: couchbase
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"
    volumes:
      - .:/opt/couchbase/var
    networks:
      - lab

networks:
  lab:
    external: true
